name: Build and Push Docker Images
permissions:
  contents: read
  packages: write
  id-token: write

on:
  workflow_run:
    workflows: ["Update build.yaml on new submodule release"]
    types:
      - completed
  push:
    tags:
      - '*'
  workflow_dispatch:
  
env:
  REPOSITORY: pulpyyyy
  REGISTRY: docker.io
  
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_addon:
    name: Build addon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [carconnectivity-addon, carconnectivity-addon-edge]
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./${{ matrix.addon }}"
          
      - name: Publish builder
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --addon \
            --all \
            --docker-hub "${{ env.REGISTRY }}" \
            --target /data/${{ matrix.addon }} \
            --docker-hub ${{ env.REPOSITORY }} \
            --docker-hub-check \
            --docker-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password ${{ secrets.DOCKERHUB_TOKEN }}